### ISSUE TITLE
can we repeat this process and get more and more urls of the domain

### ISSUE THREAD

**Issue by vijay922** [thevillagehacker/urlscrapy#1]
cat 2.txt | while read url;do urlscrapy -u $url | grep walmart.com | grep -vE 'Target URL' | sort -u | uniq 2>/dev/null >> 2.txt ; done

**Comment by thevillagehacker** [comment]
Hi Vijay,

As of now the basic url scraping feature is added and the other features to pipe the stdout to other tools is still in the development. Soon will be publishing those features here, meanwhile you can contribute as well to this repo. Please feel free to create pull request.

Happy Hacking!

thanks,
-NJ
